name: deploy-container

on:
  push:
    branches:
      - master # repo "main" istifadə edirsə, buranı main edin
    paths:
      - "packages/container/**"

defaults:
  run:
    working-directory: ./packages/container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: packages/container/package-lock.json

      - run: npm install
      - run: npm run build

      # AWS CLI (variant 1: hazır action)
      - uses: shinyinc/action-aws-cli@v1.2

      - name: Sync to S3
        run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }} # tövsiyə olunur
